### ISSUE TITLE
day04 ex03

### ISSUE THREAD

**Issue by SKTPausanias** [42-AI/bootcamp_machine-learning#100]
* Day: 04
* Exercise: 03

![Screenshot_2020-12-25_13-40-21](https://user-images.githubusercontent.com/45973042/103135223-204feb00-46b7-11eb-8b4f-8854e2469335.png)

think the example 2 is wrong , that would be the result of doing add_polynomial_features(x, 4) instead of 5, makes more sense 

![Screenshot_2020-12-25_13-45-03](https://user-images.githubusercontent.com/45973042/103135273-758bfc80-46b7-11eb-8ef3-f04856e941ee.png)

i think that would be ok, i could be wrong tho

**Comment by ymanzi** [comment]
I confirm, i had the same

**Comment by madvid** [comment]
Thanks for the issue, the correction is made in the commit [dev 9ac91fe] in the branch dev. It will appears in the main branch in the next merge.
