### ISSUE TITLE
Examples missing a feature (`theta = n` but should be `theta = n + 1`)

### ISSUE THREAD

**Issue by Antoine-lb** [42-AI/bootcamp_machine-learning#102]
* Day: 07
* Exercise: 05

Hello 👋

The example is using a `len(theta) = n` but should be `len(theta) = n + 1` because after intercepting `x` it with a column of `1`s the two matrices are incompatible.

The current example:
```python
x = np.array([
        [ -6,  -7,  -9],
        [ 13,  -2,  14],
        [ -7,  14,  -1],
        [ -8,  -4,   6],
        [ -5, -9, 6],
        [ 1, -5, 11],
        [ 9,-11, 8]])

theta1 = np.array([3, 0.5, -6]) # missing a value (feature) here
```

What it should look like:
```python
x = np.array(...)

theta1 = np.array([0, 3, 0.5, -6]) # adding a 0 (or any value) as the first feature would solve the problem 
```

Note: the two examples have the same problem

Disclaimer: I'm new to this so maybe I got something wrong

**Comment by madvid** [comment]
No need, I have to update all the days, there are multiple corrections already made in another git repo, I just have to do it on dev and do a merge request

**Comment by Antoine-lb** [comment]
ok, I'm doing the bootcamp right now so I have many errors written down on the side, hit me up if you want some help

**Comment by madvid** [comment]
Thank you for the report about the issues, there are fixed in the branch (correction_before_session_2021). Pdf will be regenerate and then merge request will follow on dev and next on main
