### ISSUE TITLE
Inconsistency for method loss and loss_elem (ML 00 + 05)

### ISSUE THREAD

**Issue by madvid** [42-AI/bootcamp_machine-learning#113]
* Day: 02
* Exercise: 05

Inconsistency between the `loss_elem(X, Y)` and `loss(X, Y)` when constructing the class. In the previous module (ML 00 exercise concerning the cost) we are asking to code `loss_elem(yhat, y)` and `loss(yhat, y)`

**Examples**
* In the module ML 02 in examples section:

![Screen Shot 2021-11-17 at 12 06 17 PM](https://user-images.githubusercontent.com/37487348/142189300-3d9d5ab0-e003-4b1f-a2f2-d5c92d5347cf.png)

* In the module ML 00:

![Screen Shot 2021-11-17 at 12 06 03 PM](https://user-images.githubusercontent.com/37487348/142189388-64cde58e-03d6-4603-9409-40e20c7995b2.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by tflahaul** [comment]
fixed in latest version
