### ISSUE TITLE
Unbiased Variance Estimator in corection, not in subject !!!

### ISSUE THREAD

**Issue by JBarmentlo** [42-AI/bootcamp_machine-learning#120]
* Day: 00
* Exercise: 01

The correction script checks for the unbiased variance estimator, the subject formula is the biased estimator !

Unbiased estimator
```python
	def var(self, x):
		return np.sum((np.square(x - np.mean(x))) / (len(x) - 1))
```
biased estimator
```python
	def var(self, x):
		return np.mean(np.square(x - np.mean(x)))
```

This is erroneous i believe
```python
epsilon = 1e-5
assert abs(tstat.var(data) - 654661) < epsilon, err
```
My estimator's value is `654660.62` and does not pass the test.
My estimator is correct check this https://www.calculatorsoup.com/calculators/statistics/variance-calculator.php with the data from the scale `42, 7, 69, 18, 352, 3, 650, 754, 438, 2659`

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
modification of the subject to ask for sample variance and standard deviation. Modification is evaluation guideline will be done also
