### ISSUE TITLE
ML01ex01, ex02: Error in example 

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#130]
* Day: 01
* Exercise: 01, 02

the example 0 asks for `[[-19.0342574],[],[-586.66875564]` with an empty `[]` for no reason.

![image](https://user-images.githubusercontent.com/38692785/149348068-91205146-8335-47a4-8c4c-b3b941b9cd49.png)

**Comment by tflahaul** [comment]
fixed in latest version
