### ISSUE TITLE
Module 00 - Exercise 00 - Matrix: confusing instruction 

### ISSUE THREAD

**Issue by madvid** [42-AI/bootcamp_machine-learning#131]
* Day: 00
* Exercise: 00 - Matrix

Confusing instruction.

It would be better to refer to instance attributes rather than this formulation.

**Screenshots**
![image](https://user-images.githubusercontent.com/37487348/149504209-ec0d3a03-c350-48a4-96b5-0b8d05026dfd.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by tflahaul** [comment]
fixed
