### ISSUE TITLE
day06ex06: exercise/example file name difference

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#133]
* Day: 01/06(github)
* Exercise: 03/06(github) Linear Regression with Class

The subjects asks for the file `my_linear_regression.py` but the subject does a `from mylinearregression import MyLinearRegression as MyLR`

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
already fixed
![image](https://user-images.githubusercontent.com/37487348/169717848-aded65cb-5f5d-4f03-a0e1-e4b9f419b4de.png)
