### ISSUE TITLE
Day06ex06 Linear regression With Class: Wrong parameter order in example

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#135]
* Day: 01/06(github)
* Exercise: 03/06(github) Linear Regression with Class

The methods `loss_` and `loss_elem` use the parameters`(y, y_hat)`, `y_hat` being the predicted result but the example uses the inverse order: `loss_elem_(lr1.predict_(x), y)`

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by tflahaul** [comment]
fixed in latest version
