### ISSUE TITLE
correction day02ex02: 2.5 instead of 4

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#140]
* Day: 02
* Exercise: 02

One of the example indicates the result should be 2.5 but it should be 4

**Examples**
If applicable, add examples to help explain your problem.

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/151374699-2f0b4702-3da8-4ded-a546-f37c955cf7e5.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
Dupplicated issue. It has been fixed already
