### ISSUE TITLE
correction: day02ex03 (I think): wrong input values

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#141]
* Day: 02
* Exercise: 03 (I think)

There are 6 entry values but 12 output values

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/151367942-d585590a-15b1-4dcb-89ed-d86f4c219752.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
Has been fix in the corresponding repository github
