### ISSUE TITLE
correction day02ex04: 3 values expected but should be 7

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#142]
* Day: 02
* Exercise: 04

The exercise inputs 7 thetas but outputs 3 gradients

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/151369187-50fd0d71-2c0f-4bfc-92e0-4f70b95c5883.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
This issue has been already fixed
