### ISSUE TITLE
Day03ex00: Example gives an array (instead of a vector

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#146]
* Day: 03
* Exercise: 00

The function asks for a vector but the subjet's examples gives an array instead of a column vector

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/155174623-cd25b43c-f5ed-43c4-bb2e-21c951e61722.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
Oh, ok. But I think it is fine. From a numpy perspective, a vector is a numpy array of shape (m,1). So for me there is no mistake @RobertsOwen

**Comment by madvid** [comment]
If you are fine by now with it, you can close the issue

**Comment by RobertsOwen** [comment]
@madvid Yes, but here the subjects does not give vector, it gives array of shape `(m,)`, 1d array

**Comment by madvid** [comment]
The output of the sigmoid seems to be a numpy array of shape (m,1) to me

**Comment by madvid** [comment]
ah ok, not the first input x.

**Comment by madvid** [comment]
I took the issue and added some precision in the docstring of the sigmoid_ function
