### ISSUE TITLE
Day03ex01: Function name missing a _ in examples

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#147]
* Day: 03
* Exercise: 01

The subject gives the function header as `logistic_predict_` but the examples ask for `logistic_predict`

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/155178392-7553424a-1def-4574-a0c0-0014f4d07c3b.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
as been fixed already

**Comment by madvid** [comment]
@qfeuilla branch `147-day03ex01-function-name-missing-a-_-in-examples` has to be deleted
