### ISSUE TITLE
Day03ex02: extra parenthesis in loss function

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#148]
* Day: 03
* Exercise: 02

The presented loss function here has an extra closing parenthesis in the first part of the loss function

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/155181243-7d8ba66c-eec0-4d36-a9cc-c5bde331afe2.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by tflahaul** [comment]
Corrigé sur la branche latex
