### ISSUE TITLE
Formul in variance

### ISSUE THREAD

**Issue by qfeuilla** [42-AI/bootcamp_machine-learning#15]
* Day: 00
* Exercise: 02

Hello, in the formula, there is two sum with the same index of summation so it's a bit confusing

**Screenshot**
![Capture](https://user-images.githubusercontent.com/58710693/71788320-6c76cb00-3021-11ea-8b18-31c0e69e391d.PNG)

**Proposed Fixe**
![CodeCogsEqn](https://user-images.githubusercontent.com/58710693/71788405-2f5f0880-3022-11ea-9ec8-81e2bd29c63a.gif)

**Comment by madvid** [comment]
Correct remarks and correct suggestion

**Comment by ppeigne** [comment]
Done
