### ISSUE TITLE
ML03ex09 Confusion matrix: Last 2 examples uses `y_true` instead of `y`

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#162]
* Day: 03
* Exercise: 09

The examples defines `y` and `y_hat` and the first 3 examples stick with that but the 4th and 5th example use `y_true` instead of `y`

**Examples**
If applicable, add examples to help explain your problem.

```python
confusion_matrix_(y_true, y_hat, df_option=True)
[...]
confusion_matrix_(y_true, y_hat, labels=['bird', 'dog'], df_option = True)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/156364835-3f92ec4b-5831-4663-a159-5df54f70655c.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
The problem seems to be treated already. I homogenized a bit the examples and there were some latex related problem (code block on a new line + sentences in docstring too large.


Need to be closed when #185 is approved
