### ISSUE TITLE
Python03ex04 Kmeans: sklearn authorized

### ISSUE THREAD

**Issue by RobertsOwen** [42-AI/bootcamp_machine-learning#168]
* Day: 03
* Exercise: 04

The subject doesn't forbid the `sklearn` lib, letting students pass by using `sklearn.KMeans`

**Screenshots**
![image](https://user-images.githubusercontent.com/38692785/156746419-5d71845a-ebff-4bc6-937c-1db3f56bb6c6.png)

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
Wrong repository @RobertsOwen
