### ISSUE TITLE
clarification on formula

### ISSUE THREAD

**Issue by qfeuilla** [42-AI/bootcamp_machine-learning#17]
* Day: 00
* Exercise: 08

Hello, in the formula, there is needed a clarification I think

**Screenshots**
![Capture](https://user-images.githubusercontent.com/58710693/71821458-800e4a00-3092-11ea-9d77-7f7dba2dd0eb.PNG)

![CodeCogsEqn(1)](https://user-images.githubusercontent.com/58710693/71821451-7d135980-3092-11ea-8b63-32cbb791297f.gif)

**Comment by madvid** [comment]
clarification needed for the meaning of the T exponent ?

**Comment by qfeuilla** [comment]
yes I think it will be easier to understand because it's a bit hard to find the signification but it's just a suggestion

**Comment by madvid** [comment]
You think well, It is already hard for people who do not have a strong mathematical background, we will seriously consider your remark

**Comment by ppeigne** [comment]
Done :)
