### ISSUE TITLE
The instructions ask a vector of shape m * 1 as argument for x, instead of a shape m * n.

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#188]
* ML module: 00
* Exercise: 03

The instructions ask a vector of shape m * 1 as argument for x, instead of a shape m * n.

**Screenshots**
<img width="940" alt="Capture d’écran 2022-03-11 à 19 54 47" src="https://user-images.githubusercontent.com/38866430/157933653-77bc12dd-5840-4017-b494-c53e83758400.png">

**Comment by tflahaul** [comment]
we fixed this already : https://github.com/42-AI/bootcamp_machine-learning/blob/b60050817429f0e22875ade108d90729cd7315f9/module05/en.subject.tex#L693

the pdf should be updated next release ✌️
