### ISSUE TITLE
ML01 EX03 errors in examples

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#191]
* Day: ML01
* Exercise: 03

If we call our class like the examples ask, we have to change the implementation and the name of our methods

**Examples**
** lr1 = MyLR([2, 0.7]) instead of --> lr1 = MyLR(np.array([[2], [0.7]]))
** lr2 = MyLR([1, 1], 5e-8, 1500000) instead of --> lr2 = MyLR(np.array([[1], [1]]), 5e-8, 1500000)
** Several times calling predict instead of calling predict_
** Two times calling MyLR instead of calling lr2

**Comment by madvid** [comment]
I don't get it. It seems find to me. If not issue will probably be created again
