### ISSUE TITLE
Error in correction ML00 EX06

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#192]
* Day: ML00
* Exercise: EX06

The correction asks :
“Define two vectors y_hat=[[1], [2], [3], [4]] and y=[[0], [0], [0], [0]]
and pass them to the functions. loss_elem_ should return
[[0.125], [0.5], [1.125], [2]]”

But here loss_elem_ should return [[1], [4], [9], [16]] with (y - y_hat)ˆ2, not [[0.125], [0.5], [1.125], [2]] as the correction says.

**Comment by madvid** [comment]
Indeed !!
Thanks for the issue.

The fix and the PR has been performed in the corresponding repository containing the evaluation sheet.
