### ISSUE TITLE
CORRECTION ML01 EX00 The correction asks 'iterative way' but the subject doesn't

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#195]
* Day: ML01
* Exercise: 00

The correction asks 'iterative way' but the subject doesn't:

IN THE SUBJECT :
<img width="887" alt="Capture d’écran 2022-03-18 à 19 58 11" src="https://user-images.githubusercontent.com/38866430/159067675-a03aa7c4-a0dc-4942-b8e5-f8a20b985fbc.png">

IN THE CORRECTION :
<img width="740" alt="Capture d’écran 2022-03-18 à 19 56 41" src="https://user-images.githubusercontent.com/38866430/159067705-5653a5fe-132e-4029-a2fb-43d41f14941e.png">

**Comment by madvid** [comment]
Oups.
Docsting has been modified without the scale. I put back the use of for loop in the docstring.
Thanks for the contribution
