### ISSUE TITLE
CORRECTION ML01 EX01 Error in basic tests

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#196]
* Day: ML01
* Exercise: 01

The corrections asks to perform tests with y equals to '-0.75-x + 5'.
But in reality the basic tests work with y equals to -0.75 * x + 5 (not minus)

In the correction :
![Capture d’écran 2022-03-18 à 20 21 05](https://user-images.githubusercontent.com/38866430/159070915-31db424b-1938-46ad-95ef-dc6e140975eb.jpg)

**Comment by madvid** [comment]
This typo has been already fixed. Update will be available on the next update on holygraph
