### ISSUE TITLE
CORRECTION ML01 EX00 missing 'reshape(-1, 1)'

### ISSUE THREAD

**Issue by antoinedauchy** [42-AI/bootcamp_machine-learning#198]
* Day: ML01
* Exercise: EX00

A 'reshape(-1, 1) is missing:
The correction asks to test with x = np.array(range(1,11))
But the subject always give us vectors like this: 
[[1],
[2],
[3]]
Not like [1, 2, 3].
So it's better with a reshape: x = np.array(range(1,11)).reshape(-1, 1)

Correction :
![Capture d’écran 2022-03-18 à 22 23 16](https://user-images.githubusercontent.com/38866430/159085613-bdb6079d-6381-4590-9ff7-7a9c9530460f.jpg)

**Comment by madvid** [comment]
Nice issue ! clear ! I love it.
The issue has been dupplicated and open in the corresponding private repo where the correction sheet are.
The PR is merged
