### ISSUE TITLE
Day00 - Mathematical Delights

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_machine-learning#2]
# Day00: Mathematical Delights
- [x] sum
- [x] mean
- [x] variance
- [x] standard deviation  

- [x] vectors dot product
- [x] matrix-vector multiplication
- [x] matrix-matrix multiplication  

- [x] mean squared error - iterative
- [x] mean squared error - vectorized
- [x] mean squared error as linear cost function - iterative
- [x] mean squared error as linear cost function - vectorized
- [x] linear gradient - iterative
- [x] linear gradient - vectorized

**Comment by ppeigne** [comment]
Should we put alpha in the gradient computation or let it for the gradient descent only ?

**Comment by ppeigne** [comment]
meaning of m in the formulas is missing

**Comment by Talasta** [comment]
> Should we put alpha in the gradient computation or let it for the gradient descent only ?

Simplest is the better !

**Comment by Vilucas** [comment]
Exercise 05 - Matrix-vector product

Mistake in example -> mat_vec_**mult**(W, Y) instead of mat_vec_**prod**(W, Y)

**Comment by Talasta** [comment]
> Exercise 05 - Matrix-vector product
> 
> Mistake in example -> mat_vec_**mult**(W, Y) instead of mat_vec_**prod**(W, Y)

Thx for the comment 🥇

**Comment by blefeuvr** [comment]
- Starting by recoding some usefull functions and formulas used later during the week.
+ Starting by recoding some useful functions and formulas used later during the week.

ex01

- • MU is the mathematical notation of the mean, which is a real number
+ • <mu notation> is the mathematical notation of the mean, which is a real number

- None if x is an empty numpy.ndarray or if f is not a valid function.
+ None if x is an empty numpy.ndarray.

ex02

- None if x is an empty numpy.ndarray or if f is not a valid function.
+ None if x is an empty numpy.ndarray.

ex03

- None if x is an empty numpy.ndarray or if f is not a valid function.
+ None if x is an empty numpy.ndarray.

ex05

- mat_vec_mult
+ mat_vec_prod

ex08
ex10
ex12
- <formula>
+ <formula with dot product>

**Comment by Vilucas** [comment]
ex08 :
- Files to turn in :vec_mse.p
+ Files to turn in :vec_mse.p**y**
