### ISSUE TITLE
ML02 Ex06 Part1 : MSE Value

### ISSUE THREAD

**Issue by ephe42** [42-AI/bootcamp_machine-learning#202]
* Day: 02
* Exercise: 06

In the first part of the exercise when I run the test program, my output is 55736.86719810518 for the MSE instead of 57636.77729 written in the subject. Is that normal ?

## Fixed on:
- [ ] Github
- [ ] Gitlab

**Comment by madvid** [comment]
Your value was correct.

It was a mistake. Sorry for the inconvenience.
It will be fix in the PR issue #212
