### ISSUE TITLE
Module02ex06 - Wrong parameters for mse_ call in subject

### ISSUE THREAD

**Issue by arlaine4** [42-AI/bootcamp_machine-learning#205]
* Module 02
* Exercise: 06

Issue in example for **_mse_ call parameters and result_** : 
```python
myLR_age = MyLR(theta = [[1000.0], [-1.0]], alpha = 2.5e-5, max_iter = 100000)
myLR_age.fit_(X[:,0].reshape(-1,1), Y)
myLR_age.mse_(X[:,0].reshape(-1,1),Y)
#Output
57636.77729...
```

**What I did to make it work**
```python
myLR_age = MyLR(theta = [[1000.0], [-1.0]], alpha = 2.5e-5, max_iter = 100000)
myLR_age.fit_(X[:,0].reshape(-1,1), Y)
y_hat = myLR_age.predict_(X)
myLR_age.mse_(Y, y_hat)
#Output
57636.77729..
```

Also , if you set a higher max_iter value, you can (obviously) get a smaller loss value.
I think the subject should say that it's okay to have a smaller loss value if you use a significantly higher max_iter value for your model

**Comment by madvid** [comment]
En cours de fix. Clarté apporté à l'exemple +fix de la valeur de l'exemple car incorrecte.

> Also , if you set a higher max_iter value, you can (obviously) get a smaller loss value.
I think the subject should say that it's okay to have a smaller loss value if you use a significantly higher max_iter value for your model
Not necessary if one has watched the suggested video recommended at the beginning of the subject.
