### ISSUE TITLE
Petite tipo dans l'ex07 du module02 bootcamp ML

### ISSUE THREAD

**Issue by jcammas** [42-AI/bootcamp_machine-learning#216]
* Day: 02
* Exercise: 07

Y a une petite tipo dans le nom de l'exercice au dessus de la présentation de la fonction à implanter.
On peut lire textttpolynomial_model.py au lieu de polynomial_model.py

"In the textttpolynomial_model.py file, create the following function as per the instructions given below:"

merci

**Comment by tflahaul** [comment]
backslash à rajouter ici
https://github.com/42-AI/bootcamp_machine-learning/blob/0fde4a087357a505f88237787a069626b6f7cbbe/module07/en.subject.tex#L997

**Comment by madvid** [comment]
C'est fait. Merci
