### ISSUE TITLE
One directory per day

### ISSUE THREAD

**Issue by blefeuvr** [42-AI/bootcamp_machine-learning#23]
* Day: day*
* Exercise: ex*

Would be preferable to have only one directory per day and all exercices files in that directory
Thus, we would be able to import previous exercice as it is frequently recommended in the exercices!

**Comment by madvid** [comment]
Thus you mean to have for example:
 +Day01:
     |-->ex00.md
     |-->ex01.md
     |-->ex02.md
     |-->...

And concerning the "assets" and "resssources" repositories ? Should they be inside the day repository or should we have one "assets" and one "ressources" directories for all the days

**Comment by madvid** [comment]
This issue will not be treated.
