### ISSUE TITLE
Day00 - Updates post-testing

### ISSUE THREAD

**Issue by sgaydonohl** [42-AI/bootcamp_machine-learning#28]
### ex00:
- [ ] 1. dans l'exemple, la valeur retournee n'est pas explicitement un float

### ex01:
- [ ] 1. 	Possible de mettre le symbole mu plutot que "mu" dans la definition des termes de l'expression?
- [ ] 2. 	"Return None if f is not a valid function" tandis que mean ne prend pas de fonction f en parametre

### ex02:
- [ ] 1. 	"Return None if f is not a valid function" tandis que variance ne prend pas de fonction f en parametre
- [ ] 2. 	xj non defini lors de la definiton des termes de l'expression ?

### ex03:
- [ ] 1. 	"Return None if f is not a valid function" tandis que std ne prend pas de fonction f en parametre

### ex04:
- [ ] 1. 	dans l'exemple, la valeur retournee n'est pas explicitement un float

### ex08:
- [ ] 1. 	"Files to turn in : vec_mse.p": oubli du 'y' dans le nom du fichier a rendre

### ex09:
- [ ] 1. 	Rien dans Forbidden function

### ex11:
- [ ] 1. 	la notation de la formule rend confus, l'utilisation du j est peu claire, je pense qu'il faudrait specifier
- [ ] 2.    preciser que le signe "delta inversé" est un nabla, pour faciliter les recherches des futurs apprenants

### ex12:
- [ ] 1. 	dans la formule, un grand X sort de nulle part
- [ ] 2. 	dans les exemples, les resultats sont egaux a la moitie de ce que l'on trouve (sachant qu'on trouve la meme chose dans l'ex11)

**Comment by sgaydonohl** [comment]
sorry, i just noticed you re working in english in this repo, i'll be speaking english from now on

**Comment by madvid** [comment]
Thanks for your remarks,
Concerning your remarks ex11, which notation do you not understand ? 
Is it the left-hand side (\nabla(J)) or something in the right-hand one ?

**Comment by sgaydonohl** [comment]
Both actually, the thing is the formula is introduced as a function but it s the representation of nabla J for a particular j, isn't it?

**Comment by ppeigne** [comment]
For ex11 we should make it explicit that the formula works` for j = 1, ..., n`

**Comment by ppeigne** [comment]
Done
