### ISSUE TITLE
Day01 - Linear Regression

### ISSUE THREAD

**Issue by Talasta** [42-AI/bootcamp_machine-learning#3]
# Day01: Linear Regression

## Algorithm
- [x] Linear Cost Function
- [x] Linear Regression
- [x] Regularized Linear Regression (not present in the last version 13/01)
- [x] Normal Equation

## Model Evaluation
- [x] Mean Square Error
- [x] Root Mean Square Error
- [x] Mean Absolute Error (Replace by the R2score)

## edit [date:09/01/2020]
fix/phase1:
### ex00:
- [x] difference in ressource name (file and citation in .md)
- [x] name columns of the data in ressource file and in example
- [x] formula
- [x] docstring coherence with other 
- [x] verification of example after formula correction

### ex01:
- [x] docstring coherence with other 
- [x] generator method different with the one in ex00
- [x] split the exercise ? or more intermediate steps
- [x] add remark if we get nan or inf with the fit method (information of learning rate)
- [x] verification of example after formula correction

### ex02:
- [x] docstring coherence with other 
- [x] verification of example after formula correction

### ex03:
- [x] description_data.csv empty
- [x] no description_data.txt
- [x] more precision in the hint.
- [x] remark to precise to not modify the methods but we expect manipulation of the data
- [x] modify the dataset to allow a learning rate of 1e-4 or -5
- [x] verification of example after formula correction

**Comment by Talasta** [comment]
ça serai pas mal de montrer la difference entre lineaire et non lineaire

**Comment by madvid** [comment]
Du coup rajouter un item "Regression non lineaire" ?
Je suis parti sur l'idée de l'utilisation d'un dataset qui serait plutot linéaire ou qui serait une une partie linéaire au moins (j'ai pris le dataset sur kaggle correspondant au feu de forêt au brésil et un dataset sur challenge ENS concernant la consommation electrique pour faire du pricing), je dois les farfouiller pour voir si une regression lineaire s'applique sur au moins un des datasets (au moins sur une portion du data).

**Comment by Talasta** [comment]
> Du coup rajouter un item "Regression non lineaire" ?
> Je suis parti sur l'idée de l'utilisation d'un dataset qui serait plutot linéaire ou qui serait une une partie linéaire au moins (j'ai pris le dataset sur kaggle correspondant au feu de forêt au brésil et un dataset sur challenge ENS concernant la consommation electrique pour faire du pricing), je dois les farfouiller pour voir si une regression lineaire s'applique sur au moins un des datasets (au moins sur une portion du data).

Je pensais plus a bien mettre en evidence la difference en lineaire et non lineaire sans forcement voir des regressions non-linéaires. 
La mention de linéarité est énormement discuter dans la literature scientifique et c'est un point clef pour beaucoup de resolution de problème, ça serai vraiment bien que les etudiants soient capable de faire la difference entre ces 2 notions.

**Comment by madvid** [comment]
Pour être sûr, tu parles des modèles non-linéaires (modèle polynomial, gaussien, etc) ou des régressions non-linéaires (soient **A** et **B** 2 matrices de coefficients même taille et **V** un vecteur de la base de fonctions choisie, le modèle est (**A**{+-*/}**B**)x**V** ))?

**Comment by Talasta** [comment]
Des 2 mais je veux surtout pas que l'on parle de modèle non linéaire aux étudiants car on risque de les perdre.

**Comment by Talasta** [comment]
Donc du coup je préfère que l'on ne parle que de polynomes en tant que problème non linéaire. Mais si tu penses que c'est une mauvaise idée je comprendrais ^^

**Comment by madvid** [comment]
Ok je vais voir, ça me semble possible

**Comment by madvid** [comment]
J'ai reporté les changements relatés dans **bootcamp_machine-learning/BOOTCAMP_SCHEDULE.md** présent dans la branche _dev_
