### ISSUE TITLE
Day01 - Updates post-testing

### ISSUE THREAD

**Issue by riblanc** [42-AI/bootcamp_machine-learning#30]
### ex00:
- [x] 1.  Remove one equal symbol on hypothesis function.
    <img src="https://latex.codecogs.com/gif.latex?h(x)&space;==&space;\theta_0&space;&plus;&space;\theta_1x" title="h(x) == \theta_0 + \theta_1x" />
- [x] 2. It's very unclear the class accept a parameter theta and also the fact we've got to try imputing differents thetas ourselves.

### ex01:
- [x] 1. 
> "The graph with the data, the hypothesis <img src="https://latex.codecogs.com/gif.latex?h_\theta^{LGD}(age)" title="h_\theta^{LGD}(age)" /> obtained via linear gradient desent versus age _**(see example figure 1)**_"

There is no legends for any figures of the exercice stipulate the nº of figures, maybe it would be preferable to use:
>    "_**Figure 1:**_ The graph with the data (...)"

Moreover there is a typo in these sentences, "desent" -> "descent"
- [x] 2.  Inconsistent use variable names on examples (MyRL_age become MyLRage):<img src="https://zupimages.net/up/20/03/63g6.png" title="MyRL_age">

### ex02:
- [x] 1. 
         - def normalequation(self, x, y))
         + def normalequation(self, x, y):
- [ ] 2. It would be preferable to go to the new line between <img src="https://latex.codecogs.com/gif.latex?x^{(i)}" title="x^{(i)}" /> and <img src="https://latex.codecogs.com/gif.latex?\mu" title="\mu" /> 
<img src="https://zupimages.net/up/20/03/zpcu.png" title="normalequation">

### ex03:
- [x] 1. The formulation is awkward
<img src="https://zupimages.net/up/20/03/wb65.png" title="Uncle Ben">
Maybe:

> [...], _**with**_ a large power thrust comes a risk of spacecraft crash

- [x] 2. <img src="https://zupimages.net/up/20/03/h4ou.png" title=typo>
There is a typo, "exloses" -> "exploses"

- [x] 3. <img src="https://zupimages.net/up/20/03/qf5c.png" title=typo>
There is also a typo "you have _**q**_ really nice (...)" -> "you have _**a**_ really nice (...)"

**Comment by madvid** [comment]
Corrections has been made when it was possible after all the modifications.
Thanks a lot.
