### ISSUE TITLE
Day02 - Updates post-testing

### ISSUE THREAD

**Issue by sgaydonohl** [42-AI/bootcamp_machine-learning#31]
## Global notes: 
I agree with a previous issue from bcarlier, its not so cool to do exercices twice, especially cause the vectorised one is the one that we thing of first ! So maybe do it in one exercice that ask the 2 methods ?
Otherwise, really cool day, really easy exercices, it s reeeeally conforting to do exercice in less than 5min !

### ex01:
- [ ] 1. 

> We encourage you to get a look at this section of the Cross entropy Wikipedia. 

--> maybe show that "this section" is a link

### ex02:
- [x] 1.  - x are the variables of your models
	    + x are the variables of your model

### ex03:
- [x] 1. - predicted outputs (formula below).
	  + predicted outputs
there is no formula below (copy pasta from ex01)

**Comment by ppeigne** [comment]
Close :)
