### ISSUE TITLE
Day02 - Updates post-testing

### ISSUE THREAD

**Issue by madvid** [42-AI/bootcamp_machine-learning#36]
### ex00:
- [x] 1. Turn-in directory and not turning

### ex01:
- [x] 1. Turn-in directory and not turning
- [x] 2. the "*" is usually used for convolution product, prefer the \dot in the formula

### ex02:
- [x] 1. Turn-in directory and not turning
- [x] 2. After the instructions for the function it is written :
"x width will be the number of coefficients or number of coefficients + 1 if you choose to add an intercept ..."
I think it should be:
"x width will be the number of coefficients or number of coefficients - 1 if you choose to add an intercept ..."
because if we decide to add an intercept the length of theta is the (width of X) + 1 and not the opposite.
- [x] 3. The formula of the gradient might be confusing, maybe a notation closer to the one of the day 00

### ex03:
- [x] 1. Turn-in directory and not turning
- [x] 2. the "*" is usually used for convolution product, prefer the \dot in the formula
- [x] 3. In the description of the formula , there is no definition of h below has it is written

### ex04:
- [x] 1. Turn-in directory and not turning

### ex05:
- [x] 1. Turn-in directory and not turning

### ex06:
- [x] 1. Turn-in directory and not turning

### ex07:
- [x] 1. Turn-in directory and not turning

### ex08:
- [x] 1. Turn-in directory and not turning

### ex09:
- [x] 1. Turn-in directory and not turning

### ex10:
- [x] 1. Turn-in directory and not turning

**Comment by ppeigne** [comment]
@madvid need more precision about the problems with the formula :)

**Comment by ppeigne** [comment]
Done :)
