### ISSUE TITLE
d00 ex01 Mean

### ISSUE THREAD

**Issue by mli42** [42-AI/bootcamp_machine-learning#37]
* Day: 00
* Exercise: 01 (Mean)

La fonction à implementer utilise une fonction f, mais on ne retrouve pas cette fonction dans notre prototype

![Screen Shot 2020-01-20 at 11 53 28 AM](https://user-images.githubusercontent.com/52219651/72721591-b6f95b00-3b7c-11ea-87bf-08e912e06afe.png)

**Comment by ppeigne** [comment]
Done
