### ISSUE TITLE
|Day00| |ex05| : Mauvais nom de fonction dans l'exemple.

### ISSUE THREAD

**Issue by Dirty-No** [42-AI/bootcamp_machine-learning#38]
* Day: 00
* Exercise: 05

(Should have I written this in English ? If so I can rewrite it if needed)

Dans l'exemple de l'exo, une fonction "mat_vec_mult" est utilisée, cependant cette fonction n'existe ni dans le sujet de l'exercice, ni dans les précédents, et semble simplement être la fonction "mat_vec_prod" (fonction que l'on doit implémenter dans l'exercice) n'ayant pas été renommée vu que celle ci donne les même résultat que l'exemple :
(ici mon test avec mon implémentation de la "bonne" fonction)
```
W = np.array([
    [-8, 8, -6, 14, 14, -9, -4],
    [2, -11, -2, -11, 14, -2, 14],
    [-13, -2, -5, 3, -8, -4, 13],
    [2, 13, -14, -15, -14, -15, 13],
    [2, -1, 12, 3, -7, -3, -6]])
Y = np.array([2, 14, -13, 5, 12, 4, -19]).reshape((7, 1))
print(mat_vec_prod(W, Y))

Sortie:
[[ 452]
 [-285]
 [-333]
 [-182]
 [-133]]
```

Et en capture d'écran, l'exemple du ex05 (entouré en rouge):
![image](https://user-images.githubusercontent.com/54525684/72728225-27a87380-3b8d-11ea-8df9-812ea325e529.png)

Mon implémentation de la fonction (au cas où ça vienne de moi, si jamais c'est le cas, désolée):
```
import numpy as np


def dot(x, y):
    try:
        assert len(x) == len(y)
        res = 0
        for i in range(len(x)):
            res += x[i] * y[i]
        return res
    except AssertionError:
        return None


def mat_vec_prod(x, y):
    try:
        assert len(x[0]) == len(y)
        return np.asarray([dot(x[i], y) for i in range(len(x))])
    except AssertionError:
        return None

```

**Comment by ppeigne** [comment]
Done :)
