### ISSUE TITLE
Day03 - Updates post-testing

### ISSUE THREAD

**Issue by riblanc** [42-AI/bootcamp_machine-learning#39]
### ex02:
- [ ] 1.  in the prototype of reg_mse function, parameters x and y are inverted.
<img src="https://www.zupimages.net/up/20/04/vrle.png" title="proto">
So, it's not according with examples:
<img src="https://www.zupimages.net/up/20/04/4j8w.png" title="example">

### ex03:
- [ ] 1.  in the prototype of reg_linear_grad function, parameters x and y are inverted. 
<img src="https://zupimages.net/up/20/04/bs8x.png" title="proto">
So, it's not according with examples:
<img src="https://zupimages.net/up/20/04/vlai.png" title="example">
There is also a parameter alpha in excess in the function description:
<img src="https://www.zupimages.net/up/20/04/xsmr.png" title="description">

### ex04:
- [ ] 1.  in the prototype of vec_reg_linear_grad function, parameters x and y are inverted. Moreover the parameter theta is missing.
<img src="https://zupimages.net/up/20/04/xm0c.png" title="proto">
So, it's not according with examples:
<img src="https://zupimages.net/up/20/04/6y2d.png" title="example">
There is also a parameter alpha in excess in the function description:
<img src="https://zupimages.net/up/20/04/wqdt.png" title="description">

### ex06:
- [ ] 1.  in the prototype of reg_logistic_grad function, parameters x and y are inverted.
<img src="https://www.zupimages.net/up/20/04/b2vn.png" title="proto">
You can notice in the example, the parameter X and Y are also inverted, so it's according with the prototype of reg_logistic_grad, but it's pretty clumsy (and there is a comma in excess):
<img src="https://www.zupimages.net/up/20/04/g62k.png" title="example">
There is also a parameter alpha in excess in the function description:
<img src="https://zupimages.net/up/20/04/m8sg.png" title="description">

**Comment by ppeigne** [comment]
Done :)
