### ISSUE TITLE
Little issues in day01 ex01 ex02 ex3 ex04

### ISSUE THREAD

**Issue by quarkgluant** [42-AI/bootcamp_machine-learning#41]
* Day: 01
* Exercise: 01, 02, 03, 04

- [x] *ex01* issue in the cost_elem docstring

>Description:
>Calculates all the elements 0.5*M*(y_pred - y)^2 of the cost function.  

à la place de `(0.5/M)*(y_pred - y)^2 `

- [x] *ex02*

arguments manquants de fit_ 
>def fit_(theta, X, Y):

à la place de `def fit_(theta, X, Y, alpha, n_cycle):`

- [x] *ex03*
`arguments manquants de fit_ 
>def fit_(theta, X, Y):

à la place de `def fit_(theta, X, Y, alpha, n_cycle):`

- [x] *ex03*
les valeurs données dans les exemples theta1, predict_(theta1, X1), theta2, predict_(theta2, X2) 
>theta1
> array([[2.0023..],[3.9991..]])
>predict_(theta1, X1)
> array([2.0023..], [6.002..], [10.0007..], [13.99988..], [17.9990..])

correspondent à self.theta -= (0.5*alpha/M)*correct
à la place de `self.theta -= (alpha/M)*correct`

- [x] *ex04*
erreurs dans les 2 exemples avec mse_
>  print(linear_model1.mse_(Xpill, Yscore))
>    57.60304285714282

à la place de `print(linear_model1.mse_(Y_model1, Yscore))`
et pareil pour le model2

- [x] *ex05*
même erreur qu'à l'ex04 dans les exemples avec mse_

**Comment by madvid** [comment]
**Concernant l'erreur des exemples dans l'exercice 2 (et non pas exercice 3):** 
Il y avait effectivement une erreur (presence du facteur 0.5) dans la formule de la descente de gradient de la methode fit, les valeurs de theta1, predict(theta1,X1), theta2 et predict(theta2,X2) post fit sont desormais corrigées.

**Concernant l'erreur de le 04 et 05:**
Une précision a été apporté comme quoi il faut appeler predict au sein de mse (dans l'exercice 4), celle-ci spécifie aussi que les 2 arguments seront bien X et Ytrue comme arguments dans les methodes des metrics des exercices qui suivent et qu'il faut donc appeler predict au sein de la methode de la metric.
