### ISSUE TITLE
X,Y function parameters inversed

### ISSUE THREAD

**Issue by drrr-deudeu** [42-AI/bootcamp_machine-learning#44]
* Day: 03
* Exercise: 02

A clear and concise description of what the problem/misunderstanding is.
Parameters x,y inversed regarding the givens examples
**Examples**
If applicable, add examples to help explain your problem.

```python
print("Code example")
```

**Screenshots**

**Comment by riblanc** [comment]
I already open an issue about it.
https://github.com/42-AI/bootcamp_machine-learning/issues/39
