### ISSUE TITLE
Inconsistent definition regularized linear gradient 

### ISSUE THREAD

**Issue by drrr-deudeu** [42-AI/bootcamp_machine-learning#45]
* Day: 03
* Exercise: 03

A clear and concise description of what the problem/misunderstanding is.
THETA is given as: "is a vector of dimension n * 1"
although the definition is given for (n+1) terms (0 until n)

**Examples**
If applicable, add examples to help explain your problem.
Also examples are given with the same dimension for X and THETA
The same result than the examples can be obtain using only the general formula (1...n)
```python
print("Code example")
```

**Screenshots**

**Comment by ppeigne** [comment]
It is a reccurent problem of the bootcamp which implies a fundamental rework of it. The fact that the matrice of X must have a column added to match with theta0 must be clarified from the begining and used consistently along the bootcamp.

**Comment by madvid** [comment]
It might be usefull to create a Notations table with all the definition of formula and symbol see trought the bootcamp

**Comment by madvid** [comment]
I harmonized the dimension through day 00, day01 and day02.
It should be ok now, and not confuse people too much.
