### ISSUE TITLE
Day02 Ex09 Wrong objectives

### ISSUE THREAD

**Issue by Medno** [42-AI/bootcamp_machine-learning#46]
* Day: 02
* Exercise: 09

In the 'Objectives' part it says : 
```
The goal of this exercise is to recreate the function recall_score of sklearn.metrics and to
learn what represents the recall and how to measure it.
```

But it was the objectives of the previous exercice (ex08: recall_score) instead of a description of F-Score.

**Comment by ppeigne** [comment]
Done ! :)
