### ISSUE TITLE
Wrong prototype in fit (MyRidge)

### ISSUE THREAD

**Issue by Medno** [42-AI/bootcamp_machine-learning#49]
* Day: 03
* Exercise: 08

There are missing parameters in the following prototype of fit : 
```
fit_(self, lambda=1.0, max_iter=1000, tol=0.001):
```
It should be composed by a training set and true results.
**Example**
```
fit_(self, x, y, alpha, lambda=1.0, max_iter=1000[, tol=0.001]):
```

**Comment by madvid** [comment]
@matboivin  fit_(self, X, Y, alpha = 0.005, n_cycle = 1000, lambda = 1)

**Comment by matboivin** [comment]
Thanks a lot! 🤖
