### ISSUE TITLE
Day00/ex07 - Explain shortly what is Mean Squared Error

### ISSUE THREAD

**Issue by matboivin** [42-AI/bootcamp_machine-learning#58]
* Day: 00
* Exercise: 07 - Mean Squared Error

In order to avoid coding a function which wasn't understood, the purpose of some formula could be explained.

```
You must implement the following formula as a function:
$$ \frac{1}{m}\sum_{i=1}^{m}(\hat{y}_i - y_i)^2 $$
```

Maybe explain the purpose of mean square error?

**Comment by madvid** [comment]
Interlude explain the role of the of the cost function and thus the MSE, RMSE MAE
