### ISSUE TITLE
Day00 - First page

### ISSUE THREAD

**Issue by eduriez** [42-AI/bootcamp_machine-learning#60]
The first page of the subject : You have written "Day01" instead of "Day00" :)
![Screenshot from 2020-04-27 12-02-01](https://user-images.githubusercontent.com/33417059/80359978-efe15400-887e-11ea-99a6-64005f128370.png)

**Comment by madvid** [comment]
thanks for the issue, indeed at that time there was this typo. Know the title are "ModuleXX" and index span over bootcamp Python and ML
