### ISSUE TITLE
Day00/ex11 - Summary

### ISSUE THREAD

**Issue by eduriez** [42-AI/bootcamp_machine-learning#61]
"Other cost Functions" rather than "Other cost Runctions", no ;) ?
![Screenshot from 2020-04-27 12-19-01](https://user-images.githubusercontent.com/33417059/80361486-4d76a000-8881-11ea-887f-10a4d3e80ed9.png)

**Comment by madvid** [comment]
Thanks for the issue.
Typo is fixed by the commit [dev 1329441], change will appears on main branch in the next merge.
