### ISSUE TITLE
Day00/ex00: Quotted code comments != section "Authorized vector operations" 

### ISSUE THREAD

**Issue by Syberam** [42-AI/bootcamp_machine-learning#62]
* Day: 00
* Exercise: 00

The comments in the requiered built-in functions code quotting (bottom page 4) are not compatible with the section "Authorized vector operations" below (page 5)

**Examples**

```
__add__
__radd__
# add : scalars and vectors, can have errors with vectors.
```
_vs_
> "Addition between two vectors of same dimension (m * 1)"
(no scalars mentionned but it is in comment)
________
```
__sub__
__rsub__
# sub : scalars and vectors, can have errors with vectors.
```
_vs_

> "Subtraction between two vectors of same dimension (m * 1)"

idem than '__\_\_[r]add\_\___'
_______
```
__truediv__
__rtruediv__
# div : only scalars.
```
nothing about that in the section 'authorized vector operations. Should we follow the mult guidelines ?

**Comment by madvid** [comment]
Thanks for the issue.
Indeed there was an incoherence, at first we wanted to ask a behavior similar to ndarray object in Numpy, but the specifications of the authorized behaviors are those expected in a mathematical way.
This probem has been solved in a past commit (I do not have the commit tag), it will appears on main branch in the next merge from dev.

Comment has been updated and only operations (add/radd/sub/rsub ) between 2 vectors objects will be asked and expected.
