### ISSUE TITLE
Day00 / Day01 Cost Function / Vectorized Cost Function Examples 3

### ISSUE THREAD

**Issue by Paul-JULLIEN** [42-AI/bootcamp_machine-learning#63]
* Day: 00 / 01
* Exercise: 07 - 08 / 01

I think there is a mistake an the third example of the cost function exercice and I guess it's because the writter use the MSE function and not MSE / 2

We have theta = [[0], [1]]
x = [[1, 0], [1, 15], [1, -9], [1, 7], [1, 12], [1, 3], [1, -21]]

If we compute hypothesis by hand, we get : [[0], [15], [-9], [7], [12], [3], [-21]]

We have y = [[2], [14], [-13], [5], [12], [4], [-19]]

If we compute the difference hyp - y = [[-2], [1], [4], [2], [0], [-1], [-2]]

By passing at the square power, we get [[4], [1], [16], [4], [0], [1], [4]]

We sum all the components, we get 30. We have 7 examples so m = 7 and we finally divide by 2*m = 2*7 = 14 and we get 2.14285714286. But if we divide by m and not by 2*m like in the MSE function we get 4.28571428571. So I guess the mistake is from here.

Tell me if the mistake if from me.

**Comment by FlorianMuller** [comment]
There's the same mistake in the **exercices 04** of the **Day 02**

**Comment by madvid** [comment]
Thanks for the issue, it is fixed, you were right.

For this mistake in day00 and day01 (now module 05 and module06) I fixed it few times ago. But I did not see the error in day02 (module07). This is fixed by the commit [dev 74b623..].
