### ISSUE TITLE
Day01 Ex05 little mistake in the fit_ function call

### ISSUE THREAD

**Issue by Paul-JULLIEN** [42-AI/bootcamp_machine-learning#65]
* Day: 01
* Exercise: 05

for theta1 you forgot to call theta in the argument list. 
It should be : 
theta1 = fit_(x, y, theta, alpha=5e-8, max_iter=1500000)

**Comment by ezalos** [comment]
Solved with commit dbc1a504ccfc2a4edd23ec79eb0c1c8c7888c85c
