### ISSUE TITLE
Day01 ex06 exemple incorrect

### ISSUE THREAD

**Issue by gdufay** [42-AI/bootcamp_machine-learning#66]
* Day: 01
* Exercise: 06

L'exemple a des petites erreurs, la version qui matche les résults attendus

```python
import numpy as np
from my_linear_regression import MyLinearRegression as MyLR

x = np.array([[12.4956442], [21.5007972], [31.5527382], [48.9145838], [57.5088733]])
y = np.array([[37.4013816], [36.1473236], [45.7655287], [46.6793434], [59.5585554]])
lr1 = MyLR([2, 0.7])

# Example 0.0:
print(lr1.predict_(x))
# Output:array([[10.74695094],[17.05055804],[24.08691674],[36.24020866],[42.25621131]])

# Example 0.1:
print(lr1.cost_elem_(lr1.predict_(x),y))
# changement ici : toutes les valeurs d'output multipliés par 10
# Output:array([[777.2116511],[493.3699664],[723.8621816],[372.9223426],[782.8360514]])

# Example 0.2:
print(lr1.cost_(lr1.predict_(x),y))
# Output:315.0202193084312

# Example 1.0:
# changement ici: pour avoir cette output, il faut utiliser les paramètres de l'exemple de l'ex05
lr2 = MyLR([1, 1], 5e-8, 1500000)
lr2.fit_(x, y)
lr2.thetas
# Output:array([[1.40709365],[1.1150909 ]])

# Example 1.1:
print(lr2.predict_(x))
# Output:array([[15.3408728 ],[25.38243697],[36.59126492],[55.95130097],[65.53471499]])

# Example 1.2:
# changement ici: utilisation lr2 au lieu lr1
print(lr2.cost_elem_(lr2.predict_(x),y)), output * 10
# Output:array([[356.749755 ],[ 41.4286023],[ 12.6440585],[293.0443042],[222.7765992]])

# Example 1.3:
# changement ici: utilisation lr2 au lieu lr1
print(lr2.cost_(lr2.predict_(x),y))
# Output:92.66433192085971
```

**Comment by madvid** [comment]
Les exemples ne sont pas faux en réalité mais la manière dont tu comprends cost_elem_ m'interpelle sur la définition de cost_elem_

Au moment où la fonction a été rédigée, la définition de cost_elem_ fut de considérer J comme une sorte de vecteur. Ce vecteur ayant chacune de ses coordonnées correspondant à la différence entre x^(i) et y^(i) élevée au carré et pondéré par un facteur (1/2M). J étant alors la somme des coordonnées de ce vecteur simplement et n'ont pas la somme du résidu pondéré par (1/2M).

L'interprétation que tu fais de cost_elem_ est de considéré que celle-ci correspond au résidu, qui semble être plus "naturelle".

Et le fait que 4 personnes ont *thumb up* souligne que la majorité tend à cette interprétation.

**Comment by madvid** [comment]
Après bref échange, ton point de vue est le plus naturel et la majorité des gens l'adopteront.

L'issue est prise en compte et les corrections sont appliquées dans le commit: [dev 63db2a1]
Les modifications seront visibles dans la branche main au prochain merge de dev vers main.

Par contre je n'ai pas les mêmes résultats que toi:
```python
# Example 1.0:
lr2 = MyLinearRegression([1, 1], 5e-8, 1500000)
lr2.fit_(x, y)
lr2.theta
# Output:
#array([[1.40709365], [1.1150909 ]])

# Example 1.1:
lr2.predict_(x)
# Output:
#array([[15.3408728 ], [25.38243697], [36.59126492], [55.95130097], [65.53471499]])

# Example 1.2:
lr2.cost_elem_(lr2.predict_(x),y)
# Output:
array([[486.66604863],
       [115.88278416],
       [ 84.16711596],
       [ 85.96919719],
       [ 35.71448348]])
          
# Example 1.3:
lr2.cost_(lr2.predict_(x),y)
# Output:
#80.83996294128525
```
