### ISSUE TITLE
Day00 ex02 blurry phrasing around percentiles

### ISSUE THREAD

**Issue by Karocyt** [42-AI/bootcamp_machine-learning#72]
* Day: 00
* Exercise: 02

Subject and examples are blurry, at least for me

Subject
> quartile(x, percentile) : computes the 1st and 3rd quartiles, also called the 25th percentile and the 75th percentile, of a given non-empty array x, using a for-loop and returns the quartile as a float, otherwise None if x is an empty array. The first parameter is the array and the second parameter is the expected percentile.

Example:
```
>>> tstat.quartile(a, 25)
10.0
>>> tstat.quartile(a, 75)
59.0
```

**Problem**
While telling us that the first quartile is the 25th percentile, we seem to have to code a function named "quartile" and taking an arbitrary percentile as parameter.
What we usually call quartiles are only the 25th, 50th and 75th percentiles...
So either "quartile(x, percentile)" has to be replaced by "percentile(x, centile)", or by a "quartiles(x)" function returning both 1st and 3rd quartiles.
The same should hold for Python Bootcamp's TinyStatistician.

As a complete beginner, I'm not sure of my interpretation so I'm reluctant to commit any changes.

**Comment by madvid** [comment]
Thanks for the issue @Karocyt .
I took your remarks in consideration, now quartile only take a list and return 1st and 3rd quartiles.
I add new method to implement called percentile which has to behave like numpy.percentile.
