### ISSUE TITLE
Day00 ex07 subject doesn't fit examples

### ISSUE THREAD

**Issue by Karocyt** [42-AI/bootcamp_machine-learning#74]
* Day: 00
* Exercise: 07

The subject tells us:
>two functions:
>• cost_elem_( ), which computes the squared distances for all examples
>• cost_( ), which averages the distances across all examples

but both the provided docstring and the example code suggest that cost_() is just the sum of the weighted costs calculated by cost_elem_()

Docstring:
>def cost_elem_(y, y_hat):
>"""
>Description:
>Calculates all the elements (1/2*M)*(y_pred - y)^2 of the cost function.

Examples:
```python
x1 = np.array([[0.], [1.], [2.], [3.], [4.]])
theta1 = np.array([[2.], [4.]])
y_hat1 = predict(x1, theta1)
y1 = np.array([[2.], [7.], [12.], [17.], [22.]])
# Example 1:
cost_elem_(y1, y_hat1)
# Output:
array([[0.], [0.1], [0.4], [0.9], [1.6]])
# Example 2:
cost_(y1, y_hat1)
# Output:
3.0
```

The first one (subject body) makes more sense to me, to first compute squared distances, then weight it, but docstring and example are both going the other way. I don't know which was the original intent.
This needs to be fixed any way for consistency, either in body or docstring/example.

**Comment by madvid** [comment]
Thanks for the issue.
Problem treated and correction made in issue #66 and issue #101
