### ISSUE TITLE
Day01 cost function parameters inconsistencies

### ISSUE THREAD

**Issue by Karocyt** [42-AI/bootcamp_machine-learning#82]
* Day: 01
* Exercise: up to ex07 at least

There is inconsistencies between subject and examples as well as across exercices about the parameters of a cost function.
Should it take (x, y) and do the prediction job or should it be a static method taking (y_hat, y) as parameters ?
I guess the later is what is usually expected of a cost function.
Either way, I can fix it if someone can testify of the original intent.

**Examples**

Ex06:
Subject:
> cost_(self, x, y)

Examples:
```
# Example 0.2:
lr1.cost_(lr1.predict(x),y)
```

Ex 07:
Examples:
```python
print(linear_model1.mse_(Xpill, Yscore))
# 57.60304285714282
>>>print(mean_squared_error(Yscore, Y_model1))
# 57.603042857142825
>>>print(linear_model2.mse_(Xpill, Yscore))
# 232.16344285714285
>>>print(mean_squared_error(Yscore, Y_model1))
# 232.16344285714285
```
(Yeah this example last call to sklearn's mse has the wrong parameters, other thing to fix)

**Comment by madvid** [comment]
Thanks for the issue.
Good point, I think the use of staticmethod decorator is a good solution to homogenized the cost_, cost_elem_ and mse_ methods.
The correction has been reported in the commit [dev 87d63eb]. It will appears in the next merge from dev to main.
