### ISSUE TITLE
Day00/ex11: Wrong formula of R² score

### ISSUE THREAD

**Issue by Toreben** [42-AI/bootcamp_machine-learning#84]
* Day: 00
* Exercise: 11

La formule du calcul de R² donnée par le sujet est fausse.
D'après Wikipédia :
[Formule trouvée sur Wikipédia](https://fr.wikipedia.org/wiki/Coefficient_de_d%C3%A9termination)

En implémentant la formule du sujet, on obtient un résultat faux, alors que l'implémentation de celle de Wikipédia nous donne le résultat attendu.

**Comment by matboivin** [comment]
Thanks for raising this! The issue will be proceeded as soon as possible.

**Comment by ezalos** [comment]
Je me suis occupe de fix cette issue !
Voici le commit du changement : 5ec36aade06e02cf4c30c0e9831c8ef5303b1b75
