### ISSUE TITLE
wrong subject day01 ex07 

### ISSUE THREAD

**Issue by SKTPausanias** [42-AI/bootcamp_machine-learning#91]
* Day: 01
* Exercise: 07

>>>print(linear_model1.mse_(Xpill, Yscore))
# 57.60304285714282
>>>print(mean_squared_error(Yscore, Y_model1))
# 57.603042857142825
>>>print(linear_model2.mse_(Xpill, Yscore))
# 232.16344285714285
>>>print(mean_squared_error(Yscore, Y_model1))
# 232.16344285714285

the last print is (Yscore, Y_model2) instead of putting the Y_model1 again so that the result is # 232.16344285714285

**Comment by madvid** [comment]
Correction already done in a previous issue
