### ISSUE TITLE
day00 ex07 wrong output in subject 

### ISSUE THREAD

**Issue by SKTPausanias** [42-AI/bootcamp_machine-learning#92]
* Day: 00
* Exercise: 07  

<img width="1042" alt="Screen Shot 2020-12-03 at 8 10 21 PM" src="https://user-images.githubusercontent.com/45973042/101076421-a8087500-35a3-11eb-94a0-c7750635b549.png">

output from cost_(y3, y_hat3) is repeated 4.238750000000004 from the # Example 4: cost_(y2, y_hat2)
the correct answer is 2.14285714 I believe

my main

	x1 = np.array([0., 1., 2., 3., 4.])
	theta1 = np.array([2., 4.])
	y_hat1 = predict_(x1, theta1)
	y1 = np.array([2., 7., 12., 17., 22.])
	print(cost_elem_(y1, y_hat1))
	print(cost_(y1, y_hat1))

	x2 = np.array([[0.2, 2., 20.], [0.4, 4., 40.], [0.6, 6., 60.], [0.8, 8., 80.]])
	theta2 = np.array([[0.05], [1.], [1.], [1.]])
	y_hat2 = predict_(x2, theta2)
	y2 = np.array([[19.], [42.], [67.], [93.]])
	print(cost_elem_(y2, y_hat2))
	print(cost_(y2, y_hat2))

	x3 = np.array([[0], [15], [-9], [7], [12], [3], [-21]])
	theta3 = np.array([[0.], [1.]])
	y_hat3 = predict_(x3, theta3)
	y3 = np.array([[2], [14], [-13],[5], [12], [4], [-19]])
	print(cost_elem_(y3, y_hat3))
	print(cost_(y3, y_hat3))
	print(cost_(y3, y3))

#output 

[0.  0.1 0.4 0.9 1.6]

3.0

[[1.3203125]
 [0.7503125]
 [0.0153125]
 [2.1528125]]

[4.23875]

[[0.28571429]
 [0.07142857]
 [1.14285714]
 [0.28571429]
 [0.        ]
 [0.07142857]
 [0.28571429]]

[2.14285714]

[0.]

**Comment by madvid** [comment]
Update of the formula for cost_elem_ and correction of the examples realized in commits [dev 5ff555..](issue #101)  and [commit 63db2a18] (issue #66). 

It appears more natural to consider cost_elem_ as residuals between y_hat and y_true.
