### ISSUE TITLE
bad output day01 ex06

### ISSUE THREAD

**Issue by SKTPausanias** [42-AI/bootcamp_machine-learning#93]
* Day: 01
* Exercise: ex06

Output in exercise ex06 is bad cause you are told to calculate cost_el(self, x , y) and cost(self, x, y) when these functions should be receiving (y_hat , y) so the results showed up in the pdf (i achieved these results) are calculated after calling two times the preditc_ function and then applying the formula of the 1/2m etc... -> np.sum((y_hat - y) **2) / float(y.shape[0] * 2) 

Just cause in subject the test is calling cost_(predict(x), y) and they say the method is build like this cost(x, y) so someone was mistaken and in the function recalculated the y_hat when it was already being given, the real results are

[10.74695094 17.05055804 24.08691674 36.24020866 42.25621131]
195.34539903032382

also it depends if u apply the 1/2m in the formula or just 1/m with out the 2 , cause im some exercises they ask you for the 1/2m formula but the results showed in the pdf correspond to applying the 1/m (mse) like in ex01 day01

**Comment by madvid** [comment]
Thanks for the issue, this problem has been solved in a previous issue.
