### ISSUE TITLE
Day04 Ex07

### ISSUE THREAD

**Issue by ezalos** [42-AI/bootcamp_machine-learning#99]
* Day: 04
* Exercise: 07

The examples given all give the same output:
```
    array([[ -60.99 ],
    [-195.64714286],
    [ 863.46571429],
    [-644.52142857]])
 ```
But the arguments differs.

I propose this as a replacement : 

```
# Example 1:
[[ -60.99      ]
 [-195.64714286]
 [ 863.46571429]
 [-644.52142857]]

# Example 2:
[[ -68.        ]
 [-192.85714286]
 [ 886.75      ]
 [-679.14285714]]

# Example 3:
[[ -68.        ]
 [-193.07142857]
 [ 886.        ]
 [-678.71428571]]
```

There could be an error on my side, so i would like a confirmation before committing any change

**Comment by SKTPausanias** [comment]
i think you are mistaken, i got the same  results of the pdf, and they are not all the same output they change a bit , take a closer look

**Comment by madvid** [comment]
Should be fixed. In an old commit probably
